apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: "ansalemostorageaccount"
  - name: accountKey
    value: "CCZXFhnPhgJh39MCT24+ZuSAjJOrqua7hzgXZwnwNMJYwQ0VdsXXVwfzfiJF2ckzh79CVaESVFtD+AStyiu8Aw=="
  - name: containerName
    value: "general"
