kind: Service
apiVersion: v1
metadata:
  name: order-processor
  labels:
    app: order-processor-app
spec:
  selector:
    app: order-processor-app
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 31314
  type: NodePort