RESOURCE_GROUP="ansalemo-rg"
CONTAINERAPPS_ENVIRONMENT="containerappsenv"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="ansalemocontainerregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="ansalemoContainerRegistry"
AZURE_CONTAINER_REGISTRY_PASSWORD="Vj3mVRsO+LiCKQr0Y3hFYjg40ltygpnL"
DAPR_APP_ID="order-processor-app"