RESOURCE_GROUP="my-rg"
CONTAINERAPPS_ENVIRONMENT="containercontainerappsenv"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="myregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="myregistryusername"
AZURE_CONTAINER_REGISTRY_PASSWORD="myregistrypassword"
DAPR_APP_ID="order-processor-app"