kind: Service
apiVersion: v1
metadata:
  name: state-management-http-app
  labels:
    app: state-management-http-app
spec:
  selector:
    app: state-management-http-app
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 31313
  type: NodePort