apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventhubs-pubsub
  namespace: default
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString    
  # Either connectionString or eventHubNamespace. Should not be used when 
  # Azure Authentication mechanism is used.
    value: "Endpoint=sb://eventhubname.servicebus.windows.net/;SharedAccessKeyName=eventhubnamepolicy;SharedAccessKey=key;EntityPath=eventhubnamepartition"
  ## Subscriber attributes
  - name: storageAccountName
    value: "account"
  - name: storageAccountKey
    value: "key"
  - name: storageContainerName
    value: "general"
