apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order-processor"
        dapr.io/app-port: "8000"

    spec:
      containers:
      - name: order-processor
        image: container-apps-development-pubsub-orderprocessor:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: "IfNotPresent"
