apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-system
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: "<ACCOUNT>"
  - name: accountKey
    value: "<KEY>"
  - name: containerName
    value: "general"
