apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "host"
  - name: redisPassword
    value: "key"
  - name: enableTLS
    # Optional. Allowed: true, false.
    value: false 
