kind: Service
apiVersion: v1
metadata:
  name: client
  labels:
    app: grpc-client
spec:
  selector:
    app: grpc-client
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 31313
  type: NodePort