RESOURCE_GROUP="my-rg"
CONTAINERAPPS_ENVIRONMENT="containerenv"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="mycontainerregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="mycontainerregistry"
AZURE_CONTAINER_REGISTRY_PASSWORD="password"


