kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
  - protocol: TCP
    port: 50051
    nodePort: 31314
  type: NodePort