apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor-app
  template:
    metadata:
      labels:
        app: order-processor-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order-processor-app"
        dapr.io/app-port: "8000"

    spec:
      containers:
      - name: order-processor-app
        image: daprcontainerapps-order-processor:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: "IfNotPresent"
