RESOURCE_GROUP="my-rg"
CONTAINERAPPS_ENVIRONMENT="containerregistryenvironment"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="mycontainerregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="mycontainerregistry"
AZURE_CONTAINER_REGISTRY_PASSWORD="password"
STORAGE_ACCOUNT_NAME="ansalemostorageaccount"
STORAGE_ACCOUNT_CONTAINER="general"
