RESOURCE_GROUP="my-rg"
CONTAINERAPPS_ENVIRONMENT="mycontainerapenv"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="yourcontainerregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="yourcontainerregistry"
AZURE_CONTAINER_REGISTRY_PASSWORD="password"


