name: Trigger auto deployment for containerapp ansalemo-ca-actions-test-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'python/service-invocation-http/**'
    - '.github/workflows/ansalemo-ca-actions-test-2-AutoDeployTrigger-b9a07b20-d4db-4fd5-9adb-9be0bea668ca.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemocontainerregistry.azurecr.io
          username: ${{ secrets.ANSALEMOCAACTIONSTEST2_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOCAACTIONSTEST2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemocontainerregistry.azurecr.io/ansalemo-ca-actions-test-2:${{ github.sha }}
          file: ./python/service-invocation-http/Dockerfile
          context: ./python/service-invocation-http/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOCAACTIONSTEST2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-ca-actions-test-2 -g ansalemo-rg --server ansalemocontainerregistry.azurecr.io --username  ${{ secrets.ANSALEMOCAACTIONSTEST2_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOCAACTIONSTEST2_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-ca-actions-test-2 -g ansalemo-rg --image ansalemocontainerregistry.azurecr.io/ansalemo-ca-actions-test-2:${{ github.sha }}
