name: Trigger auto deployment for containerapp ansalemo-container-apps-bugtest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '../python/service-invocation-http/order-processor/**'
    - '.github/workflows/ansalemo-container-apps-bugtest-AutoDeployTrigger-0b752a90-3c2a-400f-ad41-7d43e3acd9af.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemocontainerregistry.azurecr.io
          username: ${{ secrets.ANSALEMOCONTAINERAPPSBUGTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOCONTAINERAPPSBUGTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemocontainerregistry.azurecr.io/ansalemo-container-apps-bugtest:${{ github.sha }}
          file: ../python/service-invocation-http/order-processor/Dockerfile
          context: ../python/service-invocation-http/order-processor/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOCONTAINERAPPSBUGTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-container-apps-bugtest -g ansalemo-rg --server ansalemocontainerregistry.azurecr.io --username  ${{ secrets.ANSALEMOCONTAINERAPPSBUGTEST_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOCONTAINERAPPSBUGTEST_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-container-apps-bugtest -g ansalemo-rg --image ansalemocontainerregistry.azurecr.io/ansalemo-container-apps-bugtest:${{ github.sha }}
