name: Trigger auto deployment for containerapp daprcontainerapporderprocessor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'python/service-invocation-http/order-processor/**'
    - '.github/workflows/daprcontainerapporderprocessor-AutoDeployTrigger-ad81b72a-0aa8-43a1-a313-b3c577a9c6ec.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemocontainerregistry.azurecr.io
          username: ${{ secrets.DAPRCONTAINERAPPORDERPROCESSOR_REGISTRY_USERNAME }}
          password: ${{ secrets.DAPRCONTAINERAPPORDERPROCESSOR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemocontainerregistry.azurecr.io/daprcontainerapporderprocessor:${{ github.sha }}
          file: ./python/service-invocation-http/order-processor/Dockerfile
          context: ./python/service-invocation-http/order-processor/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DAPRCONTAINERAPPORDERPROCESSOR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n daprcontainerapporderprocessor -g ansalemo-rg --server ansalemocontainerregistry.azurecr.io --username  ${{ secrets.DAPRCONTAINERAPPORDERPROCESSOR_REGISTRY_USERNAME }} --password ${{ secrets.DAPRCONTAINERAPPORDERPROCESSOR_REGISTRY_PASSWORD }}
            az containerapp update -n daprcontainerapporderprocessor -g ansalemo-rg --image ansalemocontainerregistry.azurecr.io/daprcontainerapporderprocessor:${{ github.sha }}
